version: "3.9"

x-defaults: &x-defaults
  image: local
  build: .
  stdin_open: true
  tty: true
  depends_on:
    - postgres
    - rabbitmq
    - memcached

services:
  backend:
#    command: python ./app/manage.py runserver
    container_name: backend
    ports:
      - "8000:8000"
    <<: *x-defaults

  celery:
    command: celery -A settings worker -l info -c 4
    container_name: celery
    <<: *x-defaults

  celery-beat:
    command: celery -A settings beat -l info
    container_name: celery-beat
    <<: *x-defaults

  memcached:
    image: memcached:1.6.9
    container_name: memcached
#    ports:
#      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    env_file: .env
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    env_file: .env
#    ports:
#      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

  pgadmin:
    image: dpage/pgadmin4:7.1
    container_name: pgadmin
    restart: always
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  celery-flower:
    image: mher/flower:0.9.7
    container_name: celery-flower
    restart: always
    command: ["flower", "--broker=amqp://user:password@rabbitmq:5672//", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

volumes:
  db_data: {}
  pgadmin_data: {}
