# Generated by Django 4.1.6 on 2023-03-30 20:15

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.source_path),
        ),
    ]
